#!/bin/bash

# used to create django heroku project.
# the script will prompt for the kind of project and will install
# the necessary files for the project
# $1 project name
main(){
	local project_name=$1
	echo 'Creating project folder bitch ($project_name)'
	mkdir ${project_name}
	cd ${project_name}
	echo 'Creating the virtual enviroment bitch (venv)'
	virtualenv venv --distribute
	echo 'Activating the virtual enviroment bitch'
	source venv/bin/activate
	echo 'Installing django to the virtual enviroment'
	pip install Django
	read -p "Yo bitch, Care to install psycopg2?? (y/n)" answer
	case $answer in  
  		y|Y) pip install psycopg2; 
	esac
	read -p "Yo bitch, Care to install gunicorn?? (y/n)" answer
        case $answer in  
                y|Y) pip install gunicorn; 
        esac
	read -p "Yo bitch, Care to install dj-database-url?? (y/n)" answer
        case $answer in  
                y|Y) pip install dj-database-url; 
        esac
	echo 'Creating the django project (${project_name}_app)'
	`django-admin.py startproject ${project_name}_app .`
}

main $*

