#!/bin/bash

# used to create django heroku project.
# the script will prompt for the kind of project and will install
# the necessary files for the project
# $1 project name
main(){
	local project_name=$1
	echo "Creating project folder bitch (${project_name})"
	mkdir ${project_name}
	cd ${project_name}
	echo 'Creating the virtual enviroment bitch (venv)'
	virtualenv venv --distribute
	echo 'Activating the virtual enviroment bitch'
	source venv/bin/activate
	echo 'Installing django to the virtual enviroment'
	pip install Django
	read -p "Yo bitch, Care to install psycopg2?? (y/n)" answer
	case $answer in  
  		y|Y) pip install psycopg2; 
	esac
	read -p "Yo bitch, Care to install gunicorn?? (y/n)" answer
    case $answer in  
            y|Y) pip install gunicorn; 
    esac
	read -p "Yo bitch, Care to install dj-database-url?? (y/n)" answer_dj
    case $answer_dj in  
            y|Y) pip install dj-database-url; 
    esac
	echo "Creating the django project (${project_name_app})"
	`django-admin.py startproject ${project_name}_app .`
	echo 'Yo asshole, gonna create the Procfile'
	touch Procfile
	echo 'web: python manage.py run_gunicorn -b "0.0.0.0:$PORT"' >> Procfile

	case $answer_dj in
                y|Y) 
			echo 'Appending extra configuration to the settings file'
        		echo -e '\n' >> ${project_name}_app/settings.py
        		echo  '# Parse database configuration from $DATABASE_URL' >> ${project_name}_app/settings.py
        		echo  'import dj_database_url' >> ${project_name}_app/settings.py
        		echo  "DATABASES['default'] =  dj_database_url.config()" >> ${project_name}_app/settings.py
        		echo -e '\n' >> ${project_name}_app/settings.py
        		echo "# Honor the 'X-Forwarded-Proto' header for request.is_secure()" >> ${project_name}_app/settings.py
        		echo "SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')" >> ${project_name}_app/settings.py
        esac
	echo 'Creating git ignore file'
	touch .gitignore
	echo 'venv' >> .gitignore
	echo '*.pyc' >> .gitignore
	echo 'Creating a new git repository'
	git init
	git add .
	git commit -m "init django app"
	echo 'Creating requirments file'
	pip freeze > requirments.txt
	read -p "Would you like to create a local database" answer
	case $answer in  
            y|Y) 
				read -p "Please enter your postgres username:" postgres_username
				read -p "Please enter your postgres password:" postgres_password
				

    esac
	


}

main $*

